// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering), guarded
  // so the client bundle never references the nonexistent `process`.
  const VITE_URL = import.meta.env.VITE_SUPABASE_URL;
  const VITE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  const isServer = typeof window !== 'undefined' ? false : typeof process !== 'undefined';
  const SUPABASE_URL = VITE_URL || (isServer ? process.env.SUPABASE_URL : '');
  const SUPABASE_PUBLISHABLE_KEY = VITE_KEY || (isServer ? process.env.SUPABASE_PUBLISHABLE_KEY : '');

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing env var(s): ${missing.join(', ')}. Auth unavailable.`);
    return createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
      auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
    }) as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
